before_install:
- sudo apt-get install -y -qq sshpass
script: make clean
env:
  global:
    - secure: f6GpdagATsjdLQcD9WJK3J/GsPCH1EY5HPA3MH9NJ2XlmrMmpyBwdYym11cT3OrGuWq4wm3HtjCZi45CtorvHozCsq3Qd9YDQpH3UWbklgiVfDT1qhQd4SJWzBgWT1ao+YIrir5xW/nx5xgK8zAss8tf+akkgXAY88aQRyj1ALMXkPloGeLuF4RWx3G2q/m3qYOLKCPkD5q09beHO+eNtwTuEFsI9eRqXewYYLNZR5b09mj2Jabg98ER23WWykrcFGecNt27zR522mKNnpIakbkqlSou2WikiU78NGhTbtcUBUgh/rGi/DQa3cGHVew2Z/UDbKQayNu6/M3uA6iFR/eNPEMfcEeeVuJyNByh1t9NwSXkmRqLa8BWIoGNGgebZ01CPlKWEUf5Bb1CeoXq8V6DX92wFlc4NekHGYqkgoMbtYOr7mgec7XIKUEuwkYEhX4GjkdcccIUQJrIOR0w91uBKImTHiCJ4gY8kkt0oecmXufeiujhNxszGa802RFQ6R9NArYvWLhs2scNXJwzNgfXJULJHVeDdNJqp83GpqsVWPoVAvYbMEqV8w7SF95MW7sMX/uCFqzL/8CK1Zwo8rxkTapD/xhIVKgjncazANejNCunoQMqogv4HsYFeQtFwnE8H1mC8f2WLz5/qf7peODZ4la4d87cDvJ50pDJyuk=
    - DEPLOY_USER_AT_HOST=you@myhost.me
    - DEPLOYPATH=./pushdir/ant-flaka-manual
    - DEPLOYCMD=./pushdir/ant-flaka-manual.sh 
    
after_success:
- touch ./flaka-testonly.pdf
- echo "$DEPLOY_USER_AT_HOST:$DEPLOYPATH | $DEPLOYCMD"
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass
  -e scp -o stricthostkeychecking=no flaka-*.{pdf,html} $DEPLOY_USER_AT_HOST:$DEPLOYPATH
  && sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER_AT_HOST $DEPLOYCMD
